add step-2
DeryabinRS/react-burger pull request #2
Opened 2022-03-29 02:57 UTC by DeryabinRS

2022-03-29 10:00 UTC, ChrisGerBy requested changes
Здравствуйте!
Вы проделали отличную работу!
- написаны функциональные компоненты, использованы хуки useState и useEffect;
- функциональность практически полностью реализована (обратите внимание на комментарий к компоненте Modal относительно закрытия модалки по нажатию клавиши Esc - эту функциональность необходимо дописать, чтобы перейти к следующему этапу);
- хорошая структура папок, переиспользуемые типы для ингредиентов;
- код чистый, читабельный.

Однако, есть несколько замечаний, которые нужно будет исправить (см. подробные комментарии).
Особое внимание, пожалуйста, уделите компоненте Modal: 
- не реализован портал - а смысл этого задания и был как раз разобраться с этой штукой;
-  не реализовано закрытие по нажатию Esc.

Также рекомендую использовать форматтер для. наведения порядка в коде (добавить нужные отступы/ убрать лишние пустые строки, очистка неиспользуемых импортов в компонентах и т.п.).
Для автоматического форматирования кода можно использовать:
- плагин для Вашей IDE;
- https://eslint.org/
- https://prettier.io/

Удачи в исправлении!

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/modal/modal-overlay.tsx
> +const ModalOverlay:FC<ModalOverlayType> = ({color = '#585858', children, onClose}) => {
**Надо исправить**
папка компонента ModalOverlay должна находиться, согласно заданию, в директории src/components. Вынесите, пожалуйста, этот компонент и его стили в отдельную папку.

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/app/app.tsx
> +//import { BurgerType } from "../../types/Burger";
**Надо исправить**

Вы еще планируете использовать данный код? Если да, то оставьте, пожалуйста, комментарий, в каком случае/ при каких условиях этот код будет использоваться.

Если нет, то, пожалуйста, уберите неиспользуемый код.

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/burger-ingredients/burger-ingredients.tsx
>  const CardIngredient:FC<BurgerType> = (props): JSX.Element => {
**Надо исправить**
вынесите, пожалуйста, вспомогательные компоненты в отдельные файлы.
Старайтесь придерживаться правила один файл - один компонент. Потому что когда компоненты разрастаются, файл становится очень большим - и этот код тяжелее читать.

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/app/app.tsx
> +	  }
**Надо исправить**
согласно заданию, необходимо, чтобы было выполнено:
```
есть проверка успешности выполнения запроса;
```

У Вас эта проверка отсутствует.
Пожалуйста, ознакомьтесь с документацией fetch и реализуйте необходимую проверку: 
https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0_%D1%83%D1%81%D0%BF%D0%B5%D1%88%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/app/app.tsx
>  			<AppHeader/>
**Можно лучше**
видимо с прошлого этапа у Вас осталась ошибка.
Вид header-а на макете и в Вашей реализации отличаются.

Ваша реализация:
![image](https://user-images.githubusercontent.com/45519864/160580739-2df48cd5-c66f-4f5a-b728-cef09120639e.png)


Макет: фон хедера растягивается на всю ширину экрана и отсутствует отступ сверху:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/45519864/160580979-2a8b1981-38d3-4e4c-96ff-fdcc4886ca44.png">

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +const Modal:FC<ModalType> = ({title, modalOverlayColor, children, isActive, handleCloseModal}) => {
**Надо исправить**
не реализовано закрытие модалки по нажатию клавиши Esc.
```
модальные окна закрываются при клике на крестик, на ModalOverlay или нажатием на клавишу "Esc";
```

При нажатии на крестик, ModalOverlay - закрываются. При нажатии на Esc - нет. Реализуйте, пожалуйста, данную функциональность.

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/burger-ingredients/burger-ingredients.tsx
>                  <img src={props.image_large}/>
**Надо исправить**
для img должен быть задан аттрибут alt.

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +    return (
**Надо исправить**
согласно заданию,
```
в компоненте Modal используется портал;
```

Пожалуйста, выполните этот пункт задания. Вот документация: https://ru.reactjs.org/docs/portals.html

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/order-details/order-details.tsx
> +        <div className='mt-15 mb-15'><img src={ImageDone}/></div>
**Надо исправить**
для img должен быть задан аттрибут alt.

2022-03-29 10:00 UTC, ChrisGerBy commented on src/types/Burger.ts
>  }
**Можно лучше** 
добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.
<img width="430" alt="image" src="https://user-images.githubusercontent.com/45519864/160583216-3c09431e-a9e0-4821-ab49-c5ab1feb77b7.png">

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/order-details/order-details.tsx
> +export default OrderDetails
**Можно лучше** 
добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/45519864/160583279-18b3933d-fe39-4460-adc3-509b9e6d3ad7.png">

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +                    <div className={styles.btn_close} onClick={() => handleCloseModal()}>&#10006;</div>
**Надо исправить**
согласно заданию, иконки  должны быть использованы из  подключенной UI-библиотеки: 
https://yandex-praktikum.github.io/react-developer-burger-ui-components/docs/icons

Пожалуйста, используйте иконку-крестик из библиотеки.

Также рекомендую использовать синтаксис:
```
<div onClick={handleCloseModal} />
```

Здесь Вы не передаете никаких аргументов в функцию handleCloseModal, поэтому можно писать короче.

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
>          <div>
**Надо исправить**
лишний div вокруг компоненты Button, который не выполняет никакой функции. Можно смело его убрать.

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +import React, { FC, useState } from 'react'
**Надо исправить**
неиспользуемый импорт useState. Удалите, пожалуйста.

2022-03-29 10:00 UTC, ChrisGerBy commented on src/components/app/app.tsx
> +import Modal from "../modal/modal";
**Надо исправить**
неиспользуемый импорт useState. Удалите, пожалуйста.

2022-03-29 10:21 UTC, DeryabinRS commented on src/components/modal/modal-overlay.tsx
> +const ModalOverlay:FC<ModalOverlayType> = ({color = '#585858', children, onClose}) => {
+

2022-03-29 10:21 UTC, DeryabinRS commented on src/components/app/app.tsx
> +//import { BurgerType } from "../../types/Burger";
+

2022-03-29 10:31 UTC, DeryabinRS commented on src/components/burger-ingredients/burger-ingredients.tsx
>  const CardIngredient:FC<BurgerType> = (props): JSX.Element => {
+++

2022-03-29 10:34 UTC, DeryabinRS commented on src/components/app/app.tsx
> +	  }
+++

2022-03-29 10:38 UTC, DeryabinRS commented on src/components/app/app.tsx
>  			<AppHeader/>
+++

2022-03-29 10:38 UTC, DeryabinRS commented on src/components/order-details/order-details.tsx
> +export default OrderDetails
+++

2022-03-29 10:44 UTC, DeryabinRS commented on src/components/modal/modal.tsx
> +                    <div className={styles.btn_close} onClick={() => handleCloseModal()}>&#10006;</div>
+++

2022-03-29 10:46 UTC, DeryabinRS commented on src/components/burger-constructor/burger-constructor.tsx
>          <div>
+++

2022-03-29 10:47 UTC, DeryabinRS commented on src/components/modal/modal.tsx
> +import React, { FC, useState } from 'react'
+++

2022-03-29 10:47 UTC, DeryabinRS commented on src/components/app/app.tsx
> +import Modal from "../modal/modal";
+++

2022-03-29 11:31 UTC, DeryabinRS commented on src/components/order-details/order-details.tsx
> +export default OrderDetails
+++

2022-03-29 11:31 UTC, DeryabinRS commented on src/components/app/app.tsx
>  			<AppHeader/>
+++

2022-03-29 11:31 UTC, DeryabinRS commented on src/components/app/app.tsx
> +	  }
+++

2022-03-30 07:27 UTC, ChrisGerBy requested changes
Здравствуйте!
Отличный рефакторинг! Код стал гораздо чище, улучшилось форматирование.

Вы, однако, упустили некоторые пункты "Надо исправить" из предыдущего ревью:
1. https://github.com/DeryabinRS/react-burger/pull/2#discussion_r837256786
2. https://github.com/DeryabinRS/react-burger/pull/2#discussion_r837269999

В этой итерации были добавлены еще два пункта к исправлению:
1. дублирование функции escFunction в двух компонентах;
2. излишний компонент ModalCustom, от которого можно и нужно избавиться.

Для завершения работы над этим заданием необходимо исправить все эти пункты.
Желаю успехов!

2022-03-30 07:27 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +    escFunction: any;
**Надо исправить**

логика закрытия модалки по нажатию Esc не будет отличаться для разных модалок. Это всегда проверка  условия `event.key === "Escape"` - и если true, то вызов `handleCloseModal`, который Вы уже передали внутрь модалки как пропсу.
Сейчас Вы полностью дублируете escFunction в компонентах BurgerConstructor и BurgerIngredients.  
Вместо этого рекомендую Вам перенести эту функцию внутрь компоненты Modal. В тех компонентах она Вам больше не нужна.
Также обращаю Ваше внимание на то, что использовать any при типизации - это практически бессмысленно, не дает никакой информации. В данном приложении, пожалуй, нет таких мест, где any будет единственно верным решением. Поэтому Вам следует найти подходящий тип вместо any.

2022-03-30 07:27 UTC, ChrisGerBy commented on src/components/modal-custom/modal-custom.tsx
> +const ModalCustom: FC<ModalCustomType> = ({ title, isActive, handleCloseModal, children, escFunction}) => {
**Надо исправить**
лишний код. 
ModalCustom, созданный Вами, - это лишняя обертка для Modal. Вы передаете сюда пропсы - и ровненько те же пропсы передаете дальше в Modal. В чем тогда предназначение ModalCustom? 
Рекомендую Вам постараться избавиться от этого компонента и работать напрямую с Modal.

2022-03-30 15:15 UTC, ChrisGerBy requested changes
Добрый вечер!
У Вас получилось убрать ModalCustom и перенести escFunction - отлично! Ваше приложение уже более оптимизировано.

Все еще не исправлены комментарии:
1. https://github.com/DeryabinRS/react-burger/pull/2#discussion_r837256786
2. https://github.com/DeryabinRS/react-burger/pull/2#discussion_r837269999

Также рекомендую еще раз обратится к пункту о проверке успешности запроса fetch, а также к реализации escFunction. Подробнее в комментариях.

2022-03-30 15:15 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +            document.removeEventListener("keydown", (e) => escFunction(e), false);
**Можно лучше**
```
document.addEventListener("keydown", escFunction, false);
document.removeEventListener("keydown", escFunction, false);
```
Если при вызове escFunction Вы не передаете еще дополнительные аргументы в функцию, то лучше и короче будет такая запись.

2022-03-30 15:15 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +			modalBlock.innerHTML = '';
**Надо исправить**
при написании React-приложения стоит избегать работы с DOM-деревом напрямую, а стараться использовать возможности React-а.
В данном случае Вам следует рассмотреть возможность использования `handleCloseModal` пропсы, а не чистить вручную DOM-дерево. Постарайтесь переписать эту функцию так, чтобы осталось:
```
    const escFunction = (event: any) => {
		if (event.key === "Escape") {
                   handleCloseModal();
		}
	};
```

Кроме того, следует писать точные типы, тем более что тут Вы получаете конкретный event (нажатие на клавишу). Поэтому у Вас есть возможность написать точный тип.

2022-03-30 15:15 UTC, ChrisGerBy commented on src/components/app/app.tsx
> +					throw new Error('Ошибка сервера');
**Надо исправить**
`success` - это уже свойство успешного результата запроса. То есть Вы сделали запрос => получили УСПЕШНЫЙ response => проверили поле success. Если вдруг бэкэнд изменится (уберут это поле или переименуют его или/или/или ...), то запрос-то будет успешным, а нам выдаст ошибку.
Кроме того, если вдруг пришел неуспешный запрос (например, изменился url и теперь Вы шлете запрос к старому url => это приводит к 404 ошибке - то есть путь не существует), то ошибка у Вас упадет еще на этапе response.json(), потому что у response не будет такого метода. То есть response.json() мы можем вызвать уже у успешного запроса => проверка на успешность должна быть раньше вызова response.json().

Еще раз, пожалуйста, внимательно изучите документацию fetch, как проверять успешность запроса: 
https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0_%D1%83%D1%81%D0%BF%D0%B5%D1%88%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0

2022-03-31 03:57 UTC, DeryabinRS commented on src/components/modal/modal.tsx
> +            document.removeEventListener("keydown", (e) => escFunction(e), false);
++

2022-03-31 03:58 UTC, DeryabinRS commented on src/components/modal/modal.tsx
> +			modalBlock.innerHTML = '';
++

2022-03-31 04:05 UTC, DeryabinRS commented on src/components/app/app.tsx
> +					throw new Error('Ошибка сервера');
++

2022-03-31 16:20 UTC, ChrisGerBy requested changes
Здравствуйте!
Для перехода к следующему этапу обучения Вам необходимо исправить следующие ошибки:

1. вынести каждый компонент в отдельный файл (один файл - один компонент): https://github.com/DeryabinRS/react-burger/pull/2#discussion_r837256786
2. верно реализовать проверку успешности запроса: https://github.com/DeryabinRS/react-burger/pull/2#discussion_r837259704

В документации fetch точно указано, как это делается: https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0_%D1%83%D1%81%D0%BF%D0%B5%D1%88%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0

В данной итерации Вы смешали promise и async/await синтаксис, что некорректно.

3. для всех img прописать релевантный alt: 
https://github.com/DeryabinRS/react-burger/pull/2#discussion_r837269999

https://github.com/DeryabinRS/react-burger/pull/2#discussion_r837273395

4. дать корректное название пропсе handleCloseModal либо сделать рефакторинг (см. комментарий)
5. в escFunction исправить массив зависимостей.

Успехов!

2022-03-31 16:20 UTC, ChrisGerBy commented on src/components/app/app.tsx
> +					})
**Надо исправить**
не совсем корректный синтаксис.

Вы смешали синтаксис промисов и async/await.
Нужно выбрать один из вариантов:
```
fetch(url)
   .then(() => // вот тут делается вся логика работы при успешном результате )
   .catch(() => // вот тут логика работы при неуспешном запросе )
```

или

```
const response = await fetch(url);

if( проверка успешности запроса, проверяя response (см. документацию fetch о проверке успешности)) {
   // что делаем при (не)успешном запросе
}

// что делаем в противоположном случае
```

2022-03-31 16:20 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +    handleCloseModal: (active:boolean) => void;
**Надо исправить**
некорректное название функции. Судя по названию, всегда должна закрываться модалка. А исходя из Вашего кода, она может и открываться, если передать true.
Либо нужно переименовать пропсу, либо не передавать  handleCloseModal аргумент, а сетать false выше по дереву:
```
BurgerConstructor

			<Modal isActive={isActive} handleCloseModal={() => handleToggleModal(false)}>
				<OrderDetails id={'034536'} />
			</Modal> 
```

 Также хочу обратить Ваше внимание на то, что при таком синтаксисе, где мы передаем функцию, как пропсу в другой компонент, очень к месту будет использовать useCallback:



```
BurgerConstructor


const handleCloseModal = useCallback( () => handleToggleModal(false), [ ] );

return (

			<Modal isActive={isActive} handleCloseModal={handleCloseModal}>
				<OrderDetails id={'034536'} />
			</Modal> 

)
```

2022-03-31 16:20 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +	},[isActive]);
**Надо исправить**
Эта функция НЕ зависит от isActive. Каким бы ни было значение isActive, функция будет работать одинаково. Поэтому из зависимостей следует убрать.

2022-03-31 17:23 UTC, DeryabinRS commented on src/components/app/app.tsx
> +					})
+++

2022-03-31 17:32 UTC, DeryabinRS commented on src/components/modal/modal.tsx
> +    handleCloseModal: (active:boolean) => void;
+++

2022-03-31 17:32 UTC, DeryabinRS commented on src/components/modal/modal.tsx
> +	},[isActive]);
+++

2022-04-01 06:54 UTC, ChrisGerBy reviewed
Здравствуйте!
Хорошая работа! Вы исправили все замечания. Осталось все-таки еще разобраться с проверкой успешности запроса. Синтаксис все еще неверен.
В комментарии я попыталась подробно показать, почему код работает неверно.
Пожалуйста, еще раз внимательно прочитайте документацию fetch  и реализуйте проверку, как указано в документации!

Успехов!

2022-04-01 06:54 UTC, ChrisGerBy commented on src/components/app/app.tsx
> +				console.log('Возникла проблема с вашим fetch запросом: ', error.message);
**Надо исправить**
1. неверный синтаксис. Не комбинируйте await и .then().catch() - промисы в одном запросе. Либо один синтаксис, либо другой.
2. Это неверная реализация. Например, я поменяла url на несуществующий - все равно движок зашел в then.  Это значит, что неверно работает Ваш код.

**Код:** 
![image](https://user-images.githubusercontent.com/45519864/161210443-da7885c0-6622-45ad-a9d2-6ae10822d932.png)

**Консоль браузера:** 
<img width="626" alt="image" src="https://user-images.githubusercontent.com/45519864/161210814-92d4871a-1177-480d-86e0-06599562fec8.png">

3. В очередной раз указываю на документацию fetch, там есть пример кода и как делается проверка успешности. Пожалуйста, реализуйте эту проверку в точности, как указано в документации:
https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0_%D1%83%D1%81%D0%BF%D0%B5%D1%88%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0


<img width="802" alt="image" src="https://user-images.githubusercontent.com/45519864/161210686-fb21c850-12c5-479e-80ab-09a87f5dfbaf.png">

2022-04-04 07:49 UTC, merged